application: vocal-territory-679
version: 1
runtime: php
api_version: 1
threadsafe: true

handlers:
# SERVER STATIC HTMLS AND CSS
- url: /(.*\.(htm|html|css|js|mp4|mov|webm))$
  static_files: \1
  upload: .*\.(htm|html|css|js|mp4|mov|webm)$
  application_readable: true

# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true

# Serve php scripts.
- url: /(.+\.php)$
  script: \1

- url: /
  static_files: index.html
  upload: index.html
